name: Package Unittests

on:
  push:
    branches:
      - main
  pull_request:

  schedule:
    - cron: '0 2 * * *' # run at 2 AM UTC

jobs:
  unittest:
    strategy:
      matrix:
        python-version: [3.7, 3.8, 3.9]
        platform: [ubuntu-18.04]
        include:
          - python-version: 3.9
            platform: macos-latest
      fail-fast: false
    runs-on: ${{ matrix.platform }}
    steps:
      - name: Setup Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
          architecture: x64
      - name: Checkout MultiPy
        uses: actions/checkout@v2
      - name: Install dependencies
        run: |
          set -eux
          pip install -r dev-requirements.txt
          python setup.py install
      - name: Run tests
        run: coverage run -m unittest discover --verbose --start-directory multipy/test/package/ --pattern "test_*"
      - name: Coverage
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
        run: |
          set -eux
          coverage report -m
          coverage xml

          codecov
